// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Quick2Constructor
{
    internal sealed partial class Vsix
    {
        public const string Id = "Quick2Constructor.b7da2903-e706-4c00-b09d-a03b80c402ef";
        public const string Name = "Quick2Constructor";
        public const string Description = @"Quick jump to constructor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
